### ISSUE TITLE
CSS unexpected token

### ISSUE THREAD

**Issue by scottmay2020** [Martin36/react-gauge-chart#38]
Simple npm install and attempt to run breaks application returning this message:

`/node_modules/react-gauge-chart/dist/GaugeChart/style.css:1
.percent-text{
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js]`

**Comment by aaroncrawford** [comment]
Going to guess you're using webpack, but not configured to handle vanilla css and only SCSS.  If so, adjust your css/scss testing rules like so :
`test: /\.s?css$/,`

Webpack will now be able to bring in the vanilla CSS.

**Comment by ctrlaltdylan** [comment]
Just reporting a similar issue but with `withCss` and using Next.js
