### ISSUE TITLE
Next.js issue Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by gcaggia** [Martin36/react-gauge-chart#46]
When installing and using the library in my next.js project, I got this issue:

```
./node_modules/react-gauge-chart/dist/GaugeChart/style.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-gauge-chart/dist/GaugeChart/index.js
```

**Comment by BossBele** [comment]
Got the same issue

**Comment by sunshine9249** [comment]
I've got the same issue. I tried **npm install @types/react-gauge-chart** and it worked!

**Comment by BossBele** [comment]
> I've got the same issue. I tried **npm install @types/react-gauge-chart** and it worked!

Did not work for me

**Comment by westdw** [comment]
same issue,  have @types/react-gauge-chart included and didn't solve the problem.   Have @zeit/next-css and next-sass set up in my next.config.js,  all other node modules seem to work fine. 

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module.patchedRequire [as require] (<REDACTED>\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (<REDACTED>\node_modules\react-gauge-chart\dist\GaugeChart\index.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module.patchedRequire [as require] (<REDACTED>\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (<REDACTED>\node_modules\react-gauge-chart\dist\index.js:8:42)
<REDACTED>\node_modules\react-gauge-chart\dist\GaugeChart\style.css:1
.percent-text{
^

tried importing GaugeChart normally,  also tried an alternative to not have it render server side, suspecting that was the issue

let GaugeChart: (e: GaugeChartProps) => JSX.Element;
if (process.browser) {
  GaugeChart = require('react-gauge-chart').GaugeChart;
}

that just made it error at runtime.

**Comment by shamoons** [comment]
Same - not working for me

**Comment by BossBele** [comment]
Decided to get a temporary fix.
I have forked the repo and removed the css import from the module.

Next JS users may install the module using:
`yarn add git+https://github.com/BossBele/react-gauge-chart.git`
or
`npm install git+https://github.com/BossBele/react-gauge-chart.git`

In _app.js:
`import "react-gauge-chart-nextjs-support/dist/GaugeChart/style.css";`

Use as "react-gauge-chart-nextjs-support":
`import GaugeChart from "react-gauge-chart-nextjs-support";`

This is only intended to be a temporary solution for nextJS users. Hopefully the maintainers of this project will fix this issue in the future. Meanwhile, we can't stop coding!

**Comment by younes6970** [comment]
@BossBele thanks

**Comment by BossBele** [comment]
> @BossBele thanks

@younes6970 You're welcome!

**Comment by joeleduardo** [comment]
Hi i tried your solution but is not working any news about this fix this ?

**Comment by BossBele** [comment]
@joeleduardo It was commented earlier.. Looks like the recent push was not efficient. It is fixed now

**Comment by joeleduardo** [comment]
Do you know when will be merged your changes? (to the main repo) @BossBele

**Comment by BossBele** [comment]
Not exactly Sir @joeleduardo but It is in the process. However, there is another workaround (using next-css) I am currently verifying. If it works, there won't be a need for the Pull Request to be merged. I will post here my findings.

**Comment by BossBele** [comment]
@joeleduardo there is a workaround using `next-css`
In next.config.js:
```
const withCSS = require("@zeit/next-css");

module.exports = withCSS();
```

Then use [next dynamic import with no ssr](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) to import GaugeChart:
```
const GaugeChart = dynamic(() => import("react-gauge-chart"), { ssr: false });

export default function MyComponent(props) {
  return (
                <div>
                  <GaugeChart
                    id="gauge-chart1"
                    arcsLength={[0.2, 0.3, 0.5]}
                    colors={["#EA4228", "#F5CD19", "#5BE12C"]}
                    percent={0.1}
                  />
                </div>
    )
}
```

**Comment by Martin36** [comment]
@BossBele Your pull request is merged with master now

**Comment by joeleduardo** [comment]
@BossBele i believe that `@zeit/next-css` will be deprecated

**Comment by BossBele** [comment]
@joeleduardo Oh, okay

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

 [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports)  Perfect solution. 

@joeleduardo @BossBele
